[tool.mypy]
color_output = true
error_summary = true
pretty = true
show_error_context = true
show_column_numbers = true
soft_error_limit = 20
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.isort]
profile = "black"
line_length = 88
src_paths= ["svgelements"]



[tool.black]
line-length = 88
target-version = ['py36']
include = '\.pyi?$'


[tool.flake8]
filename = "*.py"
count = true
exclude = [
    "*.pyc",
    "__pycache__",
    "svgelements.py"
    ]
indent-size = 4
max-complexity = 10
max-line-length = 88
show-source = true
statistics = true
