# Add labels to Pull-Requests based on the types of files modified
# https://github.com/actions/labeler

name: "Pull-Request labeler"
on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"