name: Python code quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 22 * * 5'

concurrency:
  group: codequality-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  analyze:

    name: Lint ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get full Python version
      id: full-python-version
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

    - name: Python Cache - ${{ matrix.os }}-python-${{ steps.full-python-version.outputs.version }}
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ matrix.os }}-python-${{ steps.full-python-version.outputs.version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade --upgrade-strategy eager pip setuptools wheel babel
        pip install --upgrade --upgrade-strategy eager pylint pyproject-flake8 flake8-deprecated black mypy isort
        pip install --upgrade --upgrade-strategy eager pillow scipy>=1.7.1 numpy

    - name: Create output directory
      run: mkdir -p artifacts

    - name: Analyse with pylint
      id: pylint
      continue-on-error: true
      run: |
        pylint -j 0 --output-format=text:artifacts/pylint.txt,colorized svgelements

    - name: Analyse with flake8
      id: flake8
      continue-on-error: true
      run: |
        pflake8 svgelements/svgelements.py --tee --output-file=artifacts/flake8.txt

    - name: Analyse with black
      id: black
      continue-on-error: true
      run: |
        black --diff --color svgelements

    - name: Analyse with isort
      id: isort
      continue-on-error: true
      run: |
        isort svgelements -c --diff

    - name: Analyse with mypy
      id: mypy
      continue-on-error: true
      run: |
        mypy svgelements

    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: artifacts/

    - name: "Set status"
       #if: ${{ failure() }}
      run: |
        if ${{ steps.pylint.outcome != 'success' || steps.flake8.outcome != 'success' || steps.black.outcome != 'success' || steps.isort.outcome != 'success' }}; then
         exit 1
        fi
